superlists/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'lists.views.home_page', name='home'),
    url(r'^answer/$', 'lists.views.answer_page', name='answer'),
    url(r'^result/$', 'lists.views.result_page', name='result'),
    # url(r'^blog/', include('blog.urls')),

    # url(r'^admin/', include(admin.site.urls)),
)

lists/models.py
from django.db import models
from datetime import datetime

class Survey(models.Model):
    question = models.TextField(default='')
    choice1 = models.TextField(default='')
    choice2 = models.TextField(default='')
    choice3 = models.TextField(default='')
    choice4 = models.TextField(default='')
    answer1 = models.IntegerField(default=0)
    answer2 = models.IntegerField(default=0)
    answer3 = models.IntegerField(default=0)
    answer4 = models.IntegerField(default=0)
    time = models.DateTimeField(default=datetime.now, blank=True)

lists/views.py
from django.shortcuts import redirect, render
from lists.models import Survey
from datetime import datetime

def home_page(request):
    if request.method == 'POST'and request.POST.get(
                                    'add_survey', '') == 'Submit':
        question_text = request.POST['question']
        choice1 = request.POST['choice_1']
        choice2 = request.POST['choice_2']
        choice3 = request.POST['choice_3']
        choice4 = request.POST['choice_4']
        Survey.objects.create(question = question_text, choice1=choice1 ,
                             choice2 = choice2, choice3 = choice3, 
                             choice4 = choice4,time = datetime.now())
        return redirect('/')

    if request.method == 'POST'and request.POST.get(
                                    'nextpage', '') == 'Answer':
        return redirect('/answer/')

    return render(request, 'home.html')

def answer_page(request):

    showquestion = Survey.objects.all()
    if request.method == 'POST'and request.POST.get(
                                    'homepage', '') == 'Add_Question':
        return redirect('/')

    if request.method == 'POST'and request.POST.get(
                                    'add_answer', '') == 'Submit':
        for i in showquestion:
            result = request.POST[i.question]
            if result == i.choice1:
                i.answer1 = int(i.answer1)+1
            elif result == i.choice2:
                i.answer2 = int(i.answer2)+1
            elif result == i.choice3:
                i.answer3 = int(i.answer3)+1
            else:
                i.answer4 = int(i.answer4)+1
            i.save()

        return redirect('/result/')

    return render(request, 'answer.html',{'showquestion': showquestion})
       

def result_page(request):

    if request.method == 'POST'and request.POST.get(
                                    'back', '') == 'Back':
        return redirect('/answer/')

    showresult = Survey.objects.all()

    return render(request, 'result.html', {'showresult': showresult})

lists/templates/answer.html
<html>
    <head>
        <title>Answer Survey</title>
    </head>
    <body>
        <h1>Choose your answer</h1>

        <form method="POST">
            <table id="id_show_question" >
                <tr><td> Question </td> <td>choice 1</td> <td>choice 2</td> <td>choice 3</td> <td>choice 4</td> </tr>
                {% for i in showquestion %}
                <tr>
                    <td>{{i.question}}</td>
                    <td><input type="radio" checked ="checked" name="{{i.question}}" value="{{i.choice1}}"> {{i.choice1}} <br></td>
                    <td><input type="radio" name="{{i.question}}" value="{{i.choice2}}"> {{i.choice2}} <br></td>
                    <td><input type="radio" name="{{i.question}}" value="{{i.choice3}}"> {{i.choice3}} <br></td>
                    <td><input type="radio" name="{{i.question}}" value="{{i.choice4}}"> {{i.choice4}} <br></td>
                </tr>
                {% endfor %}
            </table>

            <input type="submit" id="id_nextpage" name="homepage" value="Add_Question">
            <input type="submit" id="id_submit" name="add_answer" value="Submit">
            {% csrf_token %}

        </form>
    </body>
</html>

lists/templates/home.html
<html>
    <head>
        <title>Survey</title>
    </head>
    <body>
        <h1>Create Your Question</h1>
        <form method="POST">
            <input name="question" id="id_question" placeholder="Key a Question" /><br><br>
            <input name="choice_1" id="id_choice_1" placeholder="Key a choice 1" /><br><br>
            <input name="choice_2" id="id_choice_2" placeholder="Key a choice 2" /><br><br>
            <input name="choice_3" id="id_choice_3" placeholder="Key a choice 3" /><br><br>
            <input name="choice_4" id="id_choice_4" placeholder="Key a choice 4" /><br><br>
            <input type="submit" id="id_submit" name="add_survey" value="Submit">
            <input type="submit" id="id_nextpage" name="nextpage" value="Answer">
            {% csrf_token %}

        </form>
    </body>
</html>

lists/templates/result.html
<html>
    <head>
        <title>Result Survey</title>
    </head>
    <body>
        <h1>Result</h1>

        <table id="id_show_question" >
            <tr><td> Question </td> <td>choice 1</td> <td>choice 2</td> <td>choice 3</td> <td>choice 4</td> <td>Time to create question</td> </tr>
            {% for i in showresult %}
            <tr>
                <td>{{i.question}}</td>
                <td>{{i.choice1}} ( {{i.answer1}} )</td> 
                <td>{{i.choice2}} ( {{i.answer2}} )</td> 
                <td>{{i.choice3}} ( {{i.answer3}} )</td> 
                <td>{{i.choice4}} ( {{i.answer4}} )</td>
                <td>{{i.time}}</td>
            </tr>
            {% endfor %}
        </table>

        <form method="POST">
            <input type="submit" id="id_back" name="back" value="Back">
            {% csrf_token %}

        </form>
    </body>
</html>